name: SonarCloud Analysis

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

jobs:
  backend-sonar:
    name: Back-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
          -Dsonar.projectKey=chiraz-dev_bobapp_backend
          -Dsonar.projectName=chiraz-dev_bobapp_backend





  frontend-sonar:
    name: Front-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@v5
        with:
          projectBaseDir: front
          args: >
            -Dsonar.organization=chiraz-dev
            -Dsonar.projectKey=chiraz-dev_bobapp_frontend
            -Dsonar.sources=src/
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
